name: Upload Code Coverage
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Swift
        uses: sersoft-gmbh/SwiftyActions@v1
        with:
          release-version: 5.6
          platform: ubuntu-18.04
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: swift test --enable-code-coverage
      - name: Generate
        run: ./.github/scripts/generate-code-coverage.sh
      - name: Upload
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./info.lcov
