name: Build, Test, and Upload Code Coverage
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Swift
        uses: sersoft-gmbh/SwiftyActions@v1
        with:
          release-version: 5.6
          platform: ubuntu-18.04
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v --enable-code-coverage
      - name: Generate Code Coverage
        run: ./.github/scripts/generate-code-coverage.sh
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./info.lcov
